### ISSUE TITLE
Rating submission in a while loop

### ISSUE THREAD

**Issue by Dedrago** [blaz-blazer/rate-my-post#1]
First of all, thank you for this plugin and allowing [ratemypost id="123"] shortcode placement in a loop. However, there is a bug there. It allows only vote in the first iteration. Thank you!

**Comment by blaz-blazer** [comment]
Hi @Dedrago , 

I'm still considering which features to include in the premium version of the plugin and allowing multiple rating widgets on a single web page is one of them. More about my thought on premium features here: https://blazzdev.com/rate-my-post-pro/ 

Nevertheless, since I probably won't have a premium version out before late spring or early summer I'll make the plugin display multiple instances till then with an admin notice explaining that this might become a premium feature in the future. 

Blaz

**Comment by Dedrago** [comment]
Hello @blaz-blazer!
I see, thank you for your response!

**Comment by blaz-blazer** [comment]
@Dedrago, 

I decided against including this as a premium feature. Allowing multiple rating widgets on a single web page will be a free feature. The functionality has been added in version 3.0.0.

**Comment by Dedrago** [comment]
Hello @blaz-blazer! Good to hear that! Thank you for this great plugin!
