### ISSUE TITLE
I am getting an error when trying to use the rating system and place a rate

### ISSUE THREAD

**Issue by alexbudin** [blaz-blazer/rate-my-post#2]
The error when i click a star rating is: Invalid nonce!

And the response is getting back in the inspector:

{"voteCount":false,"avgRating":false,"errorMsg":["Invalid nonce!"],"token":"-1","id":"-1"}

It worked for a few minutes till i tried to not show the average and total votes. I have reset all the settings and still i get the same error.

Tries in Incognito mode and diff browsers, tried logged in and no logged in admin.

Nothing seems to work.

Can you please help?

Thank you,

Alex

**Comment by alexbudin** [comment]
I am not using any caching plugin.

**Comment by alexbudin** [comment]
Yeah its a weird one. I have now logged in again and it works.

ALso why isnt there an option not to show the the number of votes? 

If i choose in settings to hide the average, it hides my star rating and all the numbers.

**Comment by blaz-blazer** [comment]
Hi @alexbudin, 

the invalid nonce issue typically appears if a page is cached for more than 24 hours due to the whole system of [WordPress nonces](https://codex.wordpress.org/WordPress_Nonces). But since you are not utilizing caching, could it be that a plugin/theme on your website is overriding the default functionality of WordPress nonces? The easiest way to debug this would be by disabling other plugins one by one and testing + changing theme to the default theme. 

As for hiding the number of votes, you can easily do that by creating a custom template. More about this in the [documentation](https://blazzdev.com/documentation/rate-my-post-documentation/#templates). 

Blaz
