### ISSUE TITLE
wp_footer enqueue

### ISSUE THREAD

**Issue by reklamasieciowa** [blaz-blazer/rate-my-post#40]
Hi, thank you for this super plugin! ;)
We're using Rate My Post 3.4.1 and we had an issue: rate-my-post.js not loading in wp_footer().
I've fixed this by changing wp_register_script: missing "null".

https://github.com/blaz-blazer/rate-my-post/blob/74af50be8d6f411699994e51c9deb632a3c2b4a9/public/class-rate-my-post-public.php#L77C3-L77C127

from: wp_register_script( $this->rate_my_post, plugin_dir_url( __FILE__ ) . 'js/rate-my-post.js', array(), $this->version, true );
to: wp_register_script( $this->rate_my_post, plugin_dir_url( __FILE__ ) . 'js/rate-my-post.js', array(), $this->version, null, true );

**Comment by blaz-blazer** [comment]
Hmm, you have 6 parameters in your function while the wp_register_script only supports 5 parameters. See here: https://developer.wordpress.org/reference/functions/wp_register_script/. So, my guess is that the null kick in instead of true which means that the script loads in header instead of footer. I want to keep the script in the footer as that's more optimal performance-wise.
